# Generated by Django 6.0.3 on 2026-04-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
