# Generated by Django 6.0.3 on 2026-04-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_contract_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('completed', 'Completed')], default='inactive', max_length=20),
        ),
    ]
